#!/bin/bash

# Create the main project directory
mkdir bioinformatics_project

# Navigate into the project directory
cd bioinformatics_project

# Create subdirectories: data, scripts, and results
mkdir data scripts results

# Inside the scripts directory, create Python files
touch scripts/generate_fasta.py scripts/dna_operations.py scripts/find_cutsites.py

# Inside the results directory, create an empty cutsite_summary.txt file
touch results/cutsite_summary.txt

# Inside the data directory, create an empty random_sequence.fasta file
touch data/random_sequence.fasta

# Create a README.md file with a brief description of the project structure
cat <<EOL > README.md
# Bioinformatics Project

This project is organized as follows:

- **data**: Contains input data files like FASTA sequences.
- **scripts**: Contains Python scripts for various bioinformatics tasks.
  - *generate_fasta.py*: Script to generate FASTA sequences.
  - *dna_operations.py*: Script for DNA-related operations.
  - *find_cutsites.py*: Script to find restriction enzyme cut sites.
- **results**: Output files generated by the scripts, such as cutsite summaries.

EOL

# Print a message indicating the setup is complete
echo "Bioinformatics project setup is complete."
